Implemented `DJANGO_EASY_AUDIT_PROPAGATE_EXCEPTIONS` setting
soynatan/django-easy-audit pull request #248
Opened 2023-03-13 18:58 UTC by dferens

Hi @jheld ,

This is a PR for https://github.com/soynatan/django-easy-audit/issues/247 , let me know if there's something I need to change.

2023-03-20 16:00 UTC, mschoettle requested changes
I am not a maintainer so am providing community feedback. Added a couple of comments.

I like this extra setting. Every once in a while I see some exceptions in pytest output that are suppressed.

2023-03-20 19:27 UTC, jheld commented on easyaudit/signals/auth_signals.py
> +        if settings.DEBUG and DEBUG_SIGNALS:
I'm open to encapsulating the logic more explicitly like that.

2023-03-20 20:31 UTC, dferens commented on easyaudit/signals/auth_signals.py
> +        if settings.DEBUG and DEBUG_SIGNALS:
done in 6c6b16ffb890b9ff21226caa7a4a7214a8f42ac5

2023-03-20 20:33 UTC, dferens commented on README.md
> +  Default is `False`. When set to `True` and Django's `DEBUG` is enabled, easyaudit will propagate exceptions occurred in own signal handlers. This is useful, unless you are using `DEBUG` in producti
@jheld need your input on this

2023-03-21 14:18 UTC, jheld commented on README.md
> +  Default is `False`. When set to `True` and Django's `DEBUG` is enabled, easyaudit will propagate exceptions occurred in own signal handlers. This is useful, unless you are using `DEBUG` in producti
Is the argument for having 2 variables (at least in the short term)? If so, I like that. We can separately issue a pending deprecation warning for the older style settings variable at any point in time (if we find that the original setting has a poor name and the behavior itself can be more configurable in nature).

2023-03-26 16:36 UTC, dferens commented
Hi @jheld , I reworked PR for a single setting and added test.

2023-04-01 18:53 UTC, mschoettle reviewed
Looks great, thanks!

There are a few lines (`raises e`) where no `should_propagate_exceptions()` is called first. Are those checks missing there?

2023-04-01 20:18 UTC, dferens commented
> There are a few lines (`raises e`) where no `should_propagate_exceptions()` is called first. Are those checks missing there?

I only modified top-level try/catch blocks, not sure if we need to change inner ones.

2023-04-17 12:18 UTC, dferens commented
Hi, how can we proceed with this?

2023-04-19 15:33 UTC, jheld approved these changes

2023-04-19 15:34 UTC, merged